name: Checks
on:
  push:
    # don't run on tags, run on commits
    # https://github.com/orgs/community/discussions/25615
    tags-ignore:
      - "**"
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  check:
    name: Checks
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v32
      - name: Set up Nix cache
        uses: nix-community/cache-nix-action@v6
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          gc-max-store-size-linux: 2G
          purge: true
          purge-prefixes: nix-${{ runner.os }}-
          purge-created: 604800 # 7 days
          purge-last-accessed: 604800 # 7 days
          purge-primary-key: never
      - name: Run Checks
        run: |
          nix flake check
          nix develop --install
          nix develop --command bash -c "pre-commit run --all-files"
